### ISSUE TITLE
Error conexion con los POD en despliegue

### ISSUE THREAD

**Issue by PascualDaniel** [Arquisoft/dede_es3b#195]
En el despliegue me sale este error al intentar acceder al Pod

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'generateKey')
    at main.106f253c.js:2:1175625
    at l (main.106f253c.js:2:1027843)
    at Generator._invoke (main.106f253c.js:2:1027631)
    at Generator.next (main.106f253c.js:2:1028272)
    at r (main.106f253c.js:2:1073901)
    at s (main.106f253c.js:2:1074104)
    at main.106f253c.js:2:1074163
    at new Promise (<anonymous>)
    at main.106f253c.js:2:1074044
    at ar (main.106f253c.js:2:1175756)

**Comment by PascualDaniel** [comment]
Al parecer es porque es necesario que sea HTTPS en vez de http, estuve mirando para cambiarlo pero con la cuenta de estudiante no deja hacer un certificado ni importarlo asi que por ahora no se como solucionar este error.
