### ISSUE TITLE
Error login Solid

### ISSUE THREAD

**Issue by PascualDaniel** [Arquisoft/dede_es3b#38]
Estuve intentando hacer un login, creo que lo tengo casi pero me este error:

`IClientRegistrar.ts:79 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
    at determineClientType (IClientRegistrar.ts:79:1)
    at handleRegistration (IClientRegistrar.ts:99:1)
    at OidcLoginHandler.handle (OidcLoginHandler.ts:92:1)
    at async ClientAuthentication.login (ClientAuthentication.ts:80:1)
    at async Session.login (Session.ts:241:1)
    at async login (Authenticator.tsx:32:1)
`

La mayoria del codigo esta aquí: [Archivo](https://github.com/Arquisoft/dede_es3b/blob/prueba-login-solid/webapp/src/authentication/Authenticator.tsx)
El error sucede porque esto es nulo _issuerConfig.scopesSupported.includes("webid")_ , no tengo idea del porque.

**Comment by PascualDaniel** [comment]
Solucionado, mirando el repo de [https://github.com/pglez82/solid-react-example](https://github.com/pglez82/solid-react-example) conseguí meterme y sacar info mirad:
![image](https://user-images.githubusercontent.com/71436553/156032711-ef00ba76-0267-407d-b8d6-d58a0c9ddb79.png)
